# Generated by Django 3.2.20 on 2025-02-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
