# Generated by Django 3.2.20 on 2025-02-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20250224_1132'),
    ]

    operations = [
    ]
