# Generated by Django 5.1.6 on 2025-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_technology_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default='', max_length=200),
        ),
    ]
