# Generated by Django 3.2.20 on 2025-02-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20250224_1149'),
    ]

    operations = [
    ]
